import { Geist, Geist_Mono } from "next/font/google";
import "primereact/resources/themes/bootstrap4-light-blue/theme.css"; // theme

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-column">
          <h1>Clay</h1>
          <h2>Chats and Relationships Analyzer (for You :) - Powered by Together.ai</h2>
        </div>
        {children}
      </body>
    </html>
  );
}
